import { Model, ModelProps } from './Model';
import { TypeApi } from '../types';
export interface BusinessProps {
    id?: number;
    name?: string;
    email?: string;
    slug?: string;
    schedule?: any;
    description?: string;
    about?: string;
    logo?: string;
    header?: string;
    phone?: string;
    cellphone?: string;
    owner_id?: number;
    city_id?: number;
    address?: string;
    address_notes?: string;
    zipcode?: string;
    location?: any;
    featured?: boolean;
    timezone?: string;
    currency?: string;
    food?: boolean;
    alcohol?: boolean;
    groceries?: boolean;
    laundry?: boolean;
    use_printer?: boolean;
    printer_id?: number;
    minimum?: number;
    delivery_price?: number;
    always_deliver?: boolean;
    tax_type?: number;
    tax?: number;
    delivery_time?: string;
    pickup_time?: string;
    service_fee?: number;
    fixed_usage_fee?: number;
    percentage_usage_fee?: number;
    enabled?: boolean;
    open?: boolean;
    lazy_load_products_recommended?: boolean;
    distance?: number;
    valid_service?: boolean;
    [metadata: string]: any;
}
export declare class Business extends Model implements ModelProps {
    id?: number;
    name?: string;
    email?: string;
    slug?: string;
    schedule?: any;
    description?: string;
    about?: string;
    logo?: string;
    header?: string;
    phone?: string;
    cellphone?: string;
    owner_id?: number;
    city_id?: number;
    address?: string;
    address_notes?: string;
    zipcode?: string;
    location?: any;
    featured?: boolean;
    timezone?: string;
    currency?: string;
    food?: boolean;
    alcohol?: boolean;
    groceries?: boolean;
    laundry?: boolean;
    use_printer?: boolean;
    printer_id?: number;
    minimum?: number;
    delivery_price?: number;
    always_deliver?: boolean;
    tax_type?: number;
    tax?: number;
    delivery_time?: string;
    pickup_time?: string;
    service_fee?: number;
    fixed_usage_fee?: number;
    percentage_usage_fee?: number;
    enabled?: boolean;
    open?: boolean;
    lazy_load_products_recommended?: boolean;
    distance?: number;
    valid_service: boolean;
    [metadata: string]: any;
    constructor(business: BusinessProps, api: TypeApi);
    /**
     * Get indentifier of model
     */
    getId(): number;
}
